apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    events {
      worker_connections 1024;
      }
    http {
      server {
        listen 80;
        location /nginx_status {
          stub_status on;
          access_log off;
        }
      }
      }