apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-svc
spec:
  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: 9113
    nodePort: 30005
  selector:
    app: nginx-exporter