version: "3.8"

services:
  c-compiler:
    image: shadikul/c-compiler
    ports:
      - "5001:5000"

  java-compiler:
    image: shadikul/java-compiler
    ports:
      - "5002:5000"

  python-compiler:
    image: shadikul/python-compiler
    ports:
      - "5003:5000"

  frontend:
    image: shadikul/frontend
    ports:
      - "80:80"


