version: '3.9'

services:
  node:
    build: .
    image: node:14
    container_name: node
    restart: always
    ports:
      - 8000:8000
    # volumes:
    #   - ./app:/app
    working_dir: /app
    command: npm start

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  redis_data:
