{
 "title": "Celestia DS KS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Intro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "<p>\n<div style=\"display: flex; justify-content: center; align-items: center; height: 150px;\">\n  <img src=\"https://cdn-assets-cloud.frontify.com/s3/frontify-cloud-files-us/eyJwYXRoIjoiZnJvbnRpZnlcL2FjY291bnRzXC8wN1wvMjIzNjI1XC9wcm9qZWN0c1wvMzEyNTQ3XC9hc3NldHNcL2E2XC81OTQ1OTI0XC85ODk5MjRiZTc4ZmQ1YmYxZTdhZmNkMmQ3MTU3MDc2NC0xNjM0NjUyMDAwLnBuZyJ9:frontify:skXd9rIvuEEG8TxJ6v8-lN_FCCUGpEC4lNXKZ0sHUYw?width=2400\" style=\"max-width: 100%; max-height: 100%;\">\n</div>\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "<p>All operators should check if they are on the latest stable version and or restart their nodes before attempting any troubleshooting changes. Celestia is still in beta and is frequently releasing fixes. You can check version, restart and update with the following commands:</p>\n\n<ul>\n  <li><code>celestia version</code></li>\n  <li><code>systemctl stop celestia-light</code></li>\n  <li><code>celestia light init --p2p.network blockspacerace</code></li>\n  <li><code>systemctl restart celestia-light</code></li>\n</ul>\n\n<p>You can check your logs using:</p>\n\n<ul>\n  <li><code>journalctl -u celestia-light.service -f</code></li>\n</ul>\n\n<p>Use the embedded <a href=\"https://docs.celestia.org/nodes/light-node/\" target=\"_blank\">link</a> to see the Celestia docs on Light Nodes.</p>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<p>\n<p>\n  <strong>\n<a href=\"https://celestia.org/\" target=\"_blank\">Website</a>\n    <span style=\"margin-left: 8px; margin-right: 8px;\">|</span>\n    <a href=\"https://docs.celestia.org/\" target=\"_blank\">Docs</a>\n<span style=\"margin-left: 8px; margin-right: 8px;\">|</span>\n    <a href=\"https://twitter.com/CelestiaOrg\" target=\"_blank\">Twitter</a>\n<span style=\"margin-left: 8px; margin-right: 8px;\">|</span>\n    <a href=\"https://discord.com/invite/YsnTPcSfWQ\" target=\"_blank\">Discord</a>\n<span style=\"margin-left: 8px; margin-right: 8px;\">|</span>\n    <a href=\"https://celestia.org/faq/\" target=\"_blank\">FAQ</a>\n <span style=\"margin-left: 8px; margin-right: 8px;\">|</span>\n    <a href=\"https://mirror.xyz/0xf3bF9DDbA413825E5DdF92D15b09C2AbD8d190dd/dIDJPGAkFeAdC98bojKn-4oHpRb5e7w0QAHTCKcsgRU\" target=\"_blank\">GLC Staked Guide</a>\n  </strong>\n</p>\n</div>\n"
   }
  },
  {
   "title": "DA Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Latest Sampled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "celestia_das_latest_sampled_ts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_node_runtime_counter_in_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Head",
   "type": "stat",
   "description": "The most recent network head",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "celestia_das_network_head", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Sampled Headers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_das_total_sampled_headers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Head",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "celestia_head", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sampled Chain Head",
   "type": "stat",
   "description": "Height of the sampled chain:- all previous headers have been sampled if matches network head. ",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_das_sampled_chain_head",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last PFB tx",
   "type": "stat",
   "description": "Time and date of last Pay For Blob transaction.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "celestia_last_pfb_timestamp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pay For Blob count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "celestia_pfb_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Head Sampled",
   "type": "stat",
   "description": "The most recent network head",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_das_head_updated_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "If Synced = 0",
   "type": "stat",
   "description": "A fully synced node will have the same head and total sampled headers (DAS) or 0 in this field. Anything more means that the node requires some syncing. ",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "celestia_das_network_head - celestia_das_total_sampled_headers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hardware Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "Processors",
   "type": "stat",
   "description": "Number of processors",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Amount of memory",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 24 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Total Disk Size",
   "type": "stat",
   "description": "Total Disk Size",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 24 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=\"ext4\", instance=\"nodeexporter:9100\", job=\"node-exporter\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Net IN (24h)",
   "type": "stat",
   "description": "Network traffic in the last hour",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total[24h]))"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 29 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1-avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))"
    }
   ]
  },
  {
   "title": "Ram Use",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 29 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - node_memory_MemFree_bytes / node_memory_MemTotal_bytes"
    }
   ]
  },
  {
   "title": "Disk Free (Total)",
   "type": "gauge",
   "description": "Free diskspace",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 29 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (sum(node_filesystem_free_bytes) / sum(node_filesystem_size_bytes))"
    }
   ]
  },
  {
   "title": "Net OUT (24h)",
   "type": "stat",
   "description": "Network traffic in the last hour",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total[24h]))"
    }
   ]
  }
 ]
}