scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginxexporter:9113']

  - job_name: 'redis-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['redisexporter:9121']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:80']
    metrics_path: '/metrics'

  - job_name: 'ceph-exporter'
    static_configs:
      - targets: ['ceph-exporter:9128']

