global:
  scrape_interval: 10s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: otel-collector
    static_configs:
      - targets: ['54.255.208.232:8888']

  - job_name: da-node-metrics
    metrics_path: /metrics
    static_configs:
      - targets: ['54.255.208.232:8889']